# Generated by Django 3.0.1 on 2020-03-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('member_type', models.CharField(max_length=50)),
                ('payment_type', models.CharField(max_length=10)),
                ('Membership_Start_date', models.DateField()),
                ('Membership_End_date', models.DateField()),
                ('rate', models.IntegerField(max_length=7)),
                ('paid', models.IntegerField(max_length=7)),
                ('due', models.IntegerField(max_length=7)),
                ('Contact_number', models.CharField(max_length=14)),
                ('Email', models.EmailField(max_length=254)),
                ('Remarks', models.CharField(max_length=255)),
            ],
        ),
    ]
